FROM node:16

# prepare build
RUN npm install -g pkg
RUN mkdir /install
WORKDIR /install
RUN wget -q https://github.com/vercel/pkg-fetch/releases/download/v3.4/node-v16.16.0-linux-x64
RUN wget -q https://github.com/vercel/pkg-fetch/releases/download/v3.4/node-v16.16.0-win-x64
RUN wget -q https://github.com/vercel/pkg-fetch/releases/download/v3.4/node-v16.16.0-macos-x64
RUN chmod 777 node-v16.16.0-*
ADD ./wordpress-mass-manage /install/
RUN npm i

# run workspace preparation
RUN mkdir /workspace
ADD ./traefik/ /workspace_/traefik
ADD ./wordpress/ /workspace_/wordpress
RUN echo "{}" > /workspace_/wordpress/subdomain_list.json

COPY ./installer/run.sh .

ENV wmm_domain docker-test.net

CMD [ "bash",  "./run.sh" ]

# docker build . -f installer/dockerfile -t wmm-install:latest --no-cache

# docker run --rm -v $(pwd)/wordpress-mass-manage/:/workspace -e wmm_domain=docker-test.net wmm-install:latest